# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Victor Kataev
title: Senior R&D Computer Vision Engineer | 10 years+ | C++, Python | 3D reconstruction | SLAM
email: kataev.victor.1234@gmail.com
website: victor1234.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: victor1234
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: victor-kataev-77a284ba
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  Senior R&D Computer Vision Engineer with over 10 years of experience and a wide range of completed projects in various fields. I have a strong understanding of how to organize work in new areas, select development and research directions, analyze results, and make informed decisions.
  I place a high emphasis on clear solution design, unit tests, documentation, code readability, continuous integration (CI), and continuous benchmarks (CB).\
  My goal is to create effective, user-friendly, and maintainable solutions.\
  \
  Location: Barcelona, Spain

content:
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      **C++** as *main language*\
      **Python** for *prototyping*\
      **Matlab** for *algorithms reference implementation and documentation*\
      **CMake** as *main framework  for build, test and benchmark project*\
      **Conan**, **vcpkg** *for crossplatform dependencies management*\
      **OpenCV**, **DLib** as *computer vision libs*\
      **Ceres,** **GTSAM** as *nonlinear solver libs*\
      **Blaze**, **Eigen** as *linear algebra  libs*\
      **GNUPlot**, **Matplotlib,** **plotly**, **dash** for *visualization*\
      **GIT** as *version control system*\
      **Catch2** as *test framework*\
      **CLion**, **NeoVim** as *IDE and code editor*

  - title: Opensource Activity # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: middle
        title: WaveletBuffer
        link: github.com/panda-official/WaveletBuffer
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A universal C++ compression library based on wavelet transformation
        description: | # this will include new lines to allow paragraphs
          I'm one of the developers in Panda team.\
          Contribution:
          - CMake/conan build system, CI
          - Python bindings and build system
          - Daubechies wavelets implementation
          - Image convolution optimization
          - Matrix manipulation optimization
          - Benchmark, unit test improvement

      - layout: middle
        title: Imalig
        link: github.com/victor1234/imalig
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Precise image alignment and camera pose estimation library. Useful for AR, drone landing, SLAM
        description: | 
          Personal project. I implemented a simple and effective solution for the famous computer vision problem.

      - layout: middle
        title: OpenCV
        link: opencv.org
        quote: >
          Well-known computer vision library
        description: |
          I mainly worked with the calibration module. I made fixes for camera models, unit/perf tests, documentation, etc.
          - [issues](https://github.com/opencv/opencv/issues?q=is%3Aissue+assignee%3Avictor1234+is%3Aclosed)
          - [PRs](https://github.com/opencv/opencv/pulls?q=is%3Apr+author%3Avictor1234+is%3Aclosed)

  - title: Experience
    layout: list
    content:

      - layout: left
        title: Tezzro
        sub_title: Computer Vision Research Engineer
        caption: June 2023 - Present
        description: |
          Multi-camera calibration
          - I calibrated several dozen cameras installed in a retail space.
          - Achieved a triangulation accuracy of less than 3 cm.
          - Identified and reported several errors in the OpenCV library related to pattern detection functions.
          - Developed a custom solution for calibrating the intrinsics and extrinsics parameters of cameras.

          Hand Positioning Accuracy Enhancement
          - Developed an algorithm for refining hand positioning using triangulation data, which significantly reduced the impact of even substantial noise, ensuring high accuracy in position determination.
          - Resilient to outliers
          - Operates in real-time

      - layout: left
        title: Artial
        sub_title: Autonomy Lead/Startup Consultant
        caption: April 2023 - May 2023
        description: |
          As an experienced engineer, I have laid a solid foundation for the successful development of software for optical navigation of UAVs.\
          My work includes:
          - Organizing and planning technical workflows
          - Creating software architecture for SLAM, obstacle avoidance, drone control, path planning, sensors, etc
          - Developing integration testing and benchmarking approaches
          - Setting up and integrating CI, CB into the development process

      - layout: left
        title: PANDA GmbH
        link: https://www.panda.technology/
        sub_title: Senior C++ Software Engineer
        caption: October 2021 - April 2023
        description: |
          - Maintenance and development of [metric](https://github.com/metric-space-ai/metric) math library
          - Development of [WaveletBuffer](https://github.com/panda-official/WaveletBuffer) library
          - Computer vision algorithms implementation
          - Statistical algorithms implementation
          - Creation of a tiny DNN engine with dense and convolutional layers from scratch
          - Daubechies wavelets algorithm optimization
          - Linear algebra algorithms optimization
          - Creation CI, CB, C++ Python bindings and pip packaging systems
          - Creation Conan package for WaveletBuffer and added it to [conan-center-index](https://github.com/conan-io/conan-center-index)

      - layout: left
        title: Huawei, R&D department, AR/VR laboratory
        link: huawei.com
        sub_title: Senior C++ Computer Vision Engineer
        caption: December 2019 — September 2021
        description: |
          - Led the development of a SLAM backend engine from scratch, successfully completing the project within three months. Efficiently organized team workflow, achieving 20% higher accuracy compared to a solution developed by another department over the course of a year.
          - Developed and implemented a real-time algorithm for precise camera localization using 2D barcodes, achieving 10 times the accuracy of standard methods
          - Developed an original Python algorithm for determining the spatial position of a VR controller with a dot pattern, achieving performance several times faster than other teams' solutions
          - Conducted research and testing of GTSAM as part of a review of modern SLAM solutions, identified a critical issue that made it less effective than Ceres Solver for SLAM applications, and successfully communicated the problem to the author on GitHub, resulting in its resolution [issue](https://github.com/borglab/gtsam/issues/248#issuecomment-613988881))
          - Researched methods for representing urban landscapes in SLAM as planes and geometric primitives, aiming to reduce memory usage and improve landscape part matching

      - layout: left
        title: Contractor (upwork.com, freelansim.ru, etc)
        link: upwork.com
        sub_title: C++ Computer Vision Engineer
        caption: May 2012 — December 2021
        description: |
          I have completed many different projects, which has given me a broad view of the industry. I have handled all stages independently, from the creation of the terms of reference to development, communication and project delivery. This experience has given me a comprehensive understanding of the entire development cycle and related areas, beyond just programming

          - Achieved 100% Job Success Rate, earned Top Rated Status, and received an 85% Client Recommendation Rate on Upwork
          - Designed and implemented a stereocamera system with two single cameras, including calibration and synchronization
          - Developed an application for one-hand large gesture recognition using a single-lens camera
          - Created a sportsmen ID identification system using a self-developed 2D-barcode with checksum
          - Engineered a hockey training device with two high-speed cameras to detect puck trajectory, velocity, and hit points
          - Developed a UAV landing system tracking a QR code with a single camera, achieving high accuracy in poor light and weather conditions
          - Built a video search engine to find modified clips (color, crop, reflection) within a video database
          - Worked on drone orthophoto map creation and structures from motion

      - layout: left
        title: Biglion
        link: biglion.ru
        sub_title: C++ Software Engineer
        caption: March 2012 — May 2012
        description: |
          - Ported mobile application from Android to Samsung Bada OS

      - layout: left
        title: Hotspot
        link: myhotspot.ru
        sub_title: C++ Augmented Reality Engineer
        caption: May 2011 — March 2012
        description: |
          - Developed a custom augmented reality engine from scratch in C++, optimized for real-time performance and low hardware requirements
          - Implemented hand gesture recognition using Kinect to create an interactive user interface
          - Created a face tracking application capable of detecting, cropping, morphing, and overlaying faces in video segments automatically
          - Led a team of two engineers, overseeing project planning and execution

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: National Research Nuclear University MEPhI (Moscow Engineering Physics Institute)
        caption: 2003 - 2009
        sub_title: Master's degree in Experimental and Theoretical Physics, specializing in Radiation Protection and Dosimetry
        quote: >
           Founded in 1942, MEPhI is the world's leading university in the field of theoretical and experimental nuclear physics
        description: | # this will include new lines to allow paragraphs
           I received a strong education in physics and mathematics and research experience.
        #
        #   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
  #
  #     Look at this cool image
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
