# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Victor Kataev
title: Computer Vision C++/Python/Matlab Linux Engineer
email: kataev.victor.1234@gmail.com
website: victor1234.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: victor1234
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: victor-kataev-77a284ba
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  Experienced R&D engineer (10 years+), with a wide range of completed projects in various fields. I have a good understanding of how to organize work in an unknown field, which development and research directions to choose, how to analyze results and make decisions.\
  I pay a lot of attention to clear solution design, unit tests, documentation, code readability, CI, CB.\
  The goal of my work is to create an effective solution, user-friendly and maintainable.

content:
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      **C++** as *main language*\
      **Python** for *prototyping*\
      **Matlab** for *algorithms reference implementation and documentation*\
      **CMake** as *main framework  for build, test and benchmark project*\
      **Conan**, **vcpkg** *for crossplatform dependencies management*\
      **OpenCV**, **DLib** as *computer vision libs*\
      **Ceres,** **GTSAM** as *nonlinear solver libs*\
      **Blaze**, **Eigen** as *linear algebra  libs*\
      **GNUPlot**, **Matplotlib,** **plotly**, **dash** for *visualization*\
      **GIT** as *version control system*\
      **Catch2** as *test framework*\
      **CLion**, **NeoVim** as *IDE and code editor*

  - title: Opensource Activity # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: middle
        title: WaveletBuffer
        link: github.com/panda-official/WaveletBuffer
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A universal C++ compression library based on wavelet transformation
        description: | # this will include new lines to allow paragraphs
          I'm one of the developers inside Panda team\
          Contribution
          - CMake/conan build system, CI
          - Python bindings and build system
          - Daubechies wavelets implementation
          - Image convolution optimization
          - Matrix manipulation optimization
          - Benchmark, unit test improvement

      - layout: middle
        title: Imalig
        link: github.com/victor1234/imalig
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Precise image alignment and camera pose estimation library. Useful for AR, drone landing, SLAM
        description: | # this will include new lines to allow paragraphs
          Personal project. I implemented simple and effective solution for famous computer vision problem.

      - layout: middle
        title: OpenCV
        link: opencv.org
        description: |
          Contribution to well known library
          - [issues](https://github.com/opencv/opencv/issues?q=is%3Aissue+assignee%3Avictor1234+is%3Aclosed)
          - [PRs](https://github.com/opencv/opencv/pulls?q=is%3Apr+author%3Avictor1234+is%3Aclosed)

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PANDA GmbH
        link: https://www.panda.technology/
        # link_text: boringcompany.com
        sub_title: Senior C++ Software Engineer
        caption: September 2021 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Maintainer and main developer of metric math lib
          - Math algorithms optimization
          - Created tiny dnn engine from scratch
          - Computer vision algorithms implementation
          - Daubechies wavelets algorithm optimization
          - Created CI, CB, c++ python bindings, pip packaging systems

      - layout: left
        title: Huawei, R&D department, AR/VR laboratory
        link: huawei.com
        sub_title: Senior C++ Computer Vision Engineer
        caption: December 2019 — September 2021
        description: |
          We mostly dealt with SLAM problems.\
          I did projects as a team member, personally, and as a project manager:
          - Precise camera localization by 2D code
          - Fast pose recognition of 3D dot pattern
          - Research modern nonlinear solver (GTSAM) (I found [issue](https://github.com/borglab/gtsam/issues/248#issuecomment-613988881] in GTSAM)
          - Create SLAM backend engine from scratch (as project lead)
          - Research the efficiency of 3D map representation as a set of geometric primitives in a SLAM problem

      - layout: left
        title: Freelancer (upwork.com, freelansim.ru, etc)
        link: upwork.com
        sub_title: C++ Computer Vision Engineer
        caption: May 2012 — December 2021
        description: |
          I have completed a large number of diverse projects, which gave me a broad perspective in the industry.And I performed all the stages from beginning to end: coordination of terms of reference, development, communication and delivery of the project, which gave me an understanding of the entire development cycle and related areas, not only programming.

          Work result on Upwork:
          - 100% Job success
          - *Top Rated* status
          - Clients who would recommend you: 85%

          Some job topics:
          - Stereocamera system with two single cams(calibration, synchronization)
          - Application for one hand big gesture recognition with monolense camera
          - Sportsmen id identification by self-developed 2d-barcode (with checksum)
          - Hockey trainer device (two high-speed cameras detected pucks trajectory, velocity and
          hit point)
          - UAV landing system (by tracking a QR code with a single camera and obtaining a relative position withhigh accuracy in poor light and weather conditions)
          - Video search engine (search modified (color, crop, reflection) clip in video database)
          - Worked with drone orthophoto map creation, structures from motion

      - layout: left
        title: Biglion
        link: biglion.ru
        sub_title: C++ Developer
        caption: March 2012 — May 2012
        description: |
          Mobile application development for Samsung Bada OS

      - layout: left
        title: Hotspot
        link: myhotspot.ru
        sub_title: Augmented Reality Software Engineer
        caption: May 2011 — March 2012
        description: |
          - Created own augment reality engine from scratch.
          - Worked with kinect (gesture interface)
          - Created application with face detection, crop, morph and paste to movie automatically.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: National Research Nuclear University MEPhI (Moscow Engineering Physics Institute)
        caption: 2003 - 2009
        sub_title: Master's degree,  Experimental and Theoretical Physics,  Radiation protection and dosimetry
        quote: >
           Founded in 1942, MEPhI is the world's leading university in the field of theoretical and experimental nuclear physics
        description: | # this will include new lines to allow paragraphs
           I received a strong education in physics and mathematics and research experience.
        #
        #   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
  #
  #     Look at this cool image
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
